### ISSUE TITLE
[ FF7 ] Unable to use controller D-Pad when naming party members

### ISSUE THREAD

**Issue by TimberAngry** [julianxhokaxhiu/FFNx#114]
Unable to use controller D-Pad when when naming characters, surely this worked in the original psx game? Forced to use analog stick. I'm using an xinput controller and using the FFNx version that is bundled with 7th heaven.

**Comment by julianxhokaxhiu** [comment]
Thanks for the report but I've personally tested this case and works fine here. Most probably the XInput driver being used through 7h does not work as expected. I've tested this scenario with a DS4 Pad w/DS4Windows in XInput mode. Works fine. Other people have tested this with an XBox controller and works fine too.

Because of this I suggest you asking support in the relative 7th support channels :)

Cheers!
