### ISSUE TITLE
[ Common ] The player moves when the Speedhack is modified

### ISSUE THREAD

**Issue by myst6re** [julianxhokaxhiu/FFNx#122]
When you press ctrl + up/down, the player moves in FF8. I think it should not, like in FF7

**Comment by julianxhokaxhiu** [comment]
Atm on FF7 it's just pure coincidence that it's working not because in code there's something preventing it but because the UP/DOWN Arrow buttons are not used in-game. If you do try to accomplish the same using a gamepad on both FF7/FF8 you'll notice the button flow goes on for both.

I'll update the title to reflect this.

**Comment by julianxhokaxhiu** [comment]
This needs to be reworked. Reopening.
