### ISSUE TITLE
[ FF7 ] Scorpion  Sentinel drawn over UI

### ISSUE THREAD

**Issue by Iniquitatis** [julianxhokaxhiu/FFNx#131]
![39140_20201111015450_1](https://user-images.githubusercontent.com/5585984/98743397-09805e00-23c1-11eb-9cca-34eae044cab2.png)

Yeah, the first boss.
It's the original Steam release (1.0.9), FFNx 1.8.0, and the only changed settings are:
`renderer_backend = 0`
`fullscreen = true`
`preserve_aspect = true`
`enable_vsync = true`
`linear_filter = false`
`enable_antialiasing = 0`
`enable_anisotropic = true`

And, just in case, important PC specs: Windows 10 2004 x64, NVIDIA GTX 460 (driver version 391.35).

**Comment by julianxhokaxhiu** [comment]
Thanks for the report, I'll check it and come back to you ASAP.

**Comment by julianxhokaxhiu** [comment]
I just did a quick check of that scene and here I'm not able to replicate that.

Looking at your video card, and driver version, it may be the bug is nested in there. What I can suggest you is trying to use the OpenGL renderer and hope you may get a better visual output.

Another thing you could try is removing the `hext` folder and try without how it looks like.

For a more quick feedback approach, feel free to reach me on Discord.

Cheers!

**Comment by Iniquitatis** [comment]
I could reproduce it only after casting Bolt on the boss, when the camera slides to the back of his left shoulder.
OpenGL produces the same result.

Also, the issue is becoming visible when the camera is going close to the floor, so the bottom part of the HUD is obstructed by it. Seems like depth testing problems of some sort.

**Comment by julianxhokaxhiu** [comment]
> I could reproduce it only after casting Bolt on the boss, when the camera slides to the back of his left shoulder.
> OpenGL produces the same result.
I'll try again to see if I can reproduce it again, by using Bolt.

> Also, the issue is becoming visible when the camera is going close to the floor, so the bottom part of the HUD is obstructed by it. Seems like depth testing problems of some sort.
This is caused by the fullscreen battle hext patch. Unfortunately we can't do much as the game on PC was never thought to have that portion of the screen visibile. Think of it as an ongoing effort to make this feature as failsafe as possible, up to a certain extent :) It can't be flagged as a bug as to be fixed we would need to have the original game source code. Reverse engineering this part is not easy at all.

**Comment by Iniquitatis** [comment]
Oh, right, I completely forgot about the hext patch. Now everything falls into place, in the original release there was a black bar, so the HUD could be safely drawn there with a depth testing.

**Comment by julianxhokaxhiu** [comment]
OOC does this bug happen also in the original release?

**Comment by Iniquitatis** [comment]
Nope, IIRC, there were no similar issues.
I mean, in the original release, the battle scene filled only the upper part of the screen, so the lower part of the depth buffer remained clean and usable for the UI.
Still, I might be wrong.

**Comment by julianxhokaxhiu** [comment]
> Nope, IIRC, there were no similar issues.
> I mean, in the original release, the battle scene filled only the upper part of the screen, so the lower part of the depth buffer remained clean and usable for the UI.
> Still, I might be wrong.

I have a feeling that this is all about "hacking" some vertex data. Most probably you will have to live with it as there's no way to fix that easily unfortunately.

If you find that the scene works out fine without the `hext` folder just remove it and feel free to play without it ( or remove the related hext file that does put the battle fullscreen, and keep the rest, feel free to hack it your way ).

Because of this I'll remove again ( and this time for good ) the bug tag. Yes, it is one but it's nothing that can be fixed ( unless you want to contribute in the Reverse Engineering, but then feel free to open a PR ).

Cheers :)

**Comment by Iniquitatis** [comment]
As much as I'd like to contribute, unfortunately, I've got no experience in that department whatsoever. So you might want to leave the "help wanted" label on the issue.

**Comment by julianxhokaxhiu** [comment]
Allright, I'll leave it this way. Thank you :)

**Comment by chrcoluk** [comment]
To add here, the way to fix this is the scene.bin, so possibly fixable by mod authors who include battle scenes in their mod.  In the few fights where this occurs its nearly always only during transition of a animation so only briefly for a second or two, its only persistent in a rare spawn in an area north of icicle village thats only visited once in the game.

**Comment by tangtang95** [comment]
In case of non-transparent battle menu, it is possible to avoid this bug by changing the viewport height for the battle scene viewport. Just change the first value of the fullscreen hext into `41B51A = 70 `. For the transparent case, I suppose we need to find a way to draw the menu more in the front of the camera. Not sure though.

**Comment by julianxhokaxhiu** [comment]
> I suppose we need to find a way to draw the menu more in the front of the camera

Yes, this issue is all about this basically. The day we will find how that's done, all we need is to raise its z-index.
