### ISSUE TITLE
[FF7] Bad Fx rendering in worldmap with upscaled textures

### ISSUE THREAD

**Issue by satsukiyatoshi** [julianxhokaxhiu/FFNx#136]
Description:
In wordmap the Fx animation (from buggy, hightwind, plane, boat...) seems to be rendered without any apha (with upscaled textures).
So it's realy dark and bad looking compared to vanilla.

FFNx version:
All (tested in stable 1.8.0 and 1.8.1.10 vanilla)

Step to reproduce:
Go in WM and use any vehicule with external textures

Exemple video:
[smoke.zip](https://github.com/julianxhokaxhiu/FFNx/files/5556300/smoke.zip)

**Comment by julianxhokaxhiu** [comment]
I did two RenderDoc captures to analyze what is going on, and I think this is related to the modded texture.

(Left: Stock, Right: Modded)
![image](https://user-images.githubusercontent.com/1237070/99457478-561ce980-292b-11eb-8dd0-9e63a7b28544.png)

Try to play with the alpha channel like on the stock texture and I'm pretty sure you should get a gray-ish smoke, rather than a black one.

**Comment by satsukiyatoshi** [comment]
solved, this file need to be set with 75% transparency
