### ISSUE TITLE
[ FF7 ] Issue with SFX playback in Tifa's Lifestream sequence.

### ISSUE THREAD

**Issue by daedrixxx2** [julianxhokaxhiu/FFNx#212]
> julianxhokaxhiu commented 14 days ago • 
I tested the scene in both vanilla and with external SFX:
-Vanilla: The SFX effects are like in the video ( PC version ) you linked, so buggy
-External SFX: Working correctly like on the PSX version, on top of Bonez Cosmo Memory pack
This means that the bug is only present in vanilla, and as I overwrite the behavior of the SFX playback, it could be I'm not inheriting some logics from the engine, which are on the other hand triggered by the engine through flevel ( field ID 111 - Id 0 - S0 Main ).
Therefore, I'd say that if you don't want to patch the flevel, you can easily use the external SFX layer.
Finally, if you want you can open a new issue mentioning only the Tifa Lifestream issue, so we can flag that as "external fix required". Because of this, I'll therefore close the current issue as all the left known bugs, that could be fixed via code, are fixed.

As I was told I'm opening this issue to ask for the patching of the flevel ( field ID 111 - Id 0 - S0 Main ) to remove the above mentioned bug triggered by the vanilla SFX playback engine.

**Comment by julianxhokaxhiu** [comment]
Short version: `use_external_sfx = true`

Long version: In order to fix this I'd need to rewrite the entire SFX playback layer of the native engine, which doesn't even benefit anyone as we now have our own external layer which does the same job, even better fixing basically bugs like this one. Because of this, I suggest you finding a way to extract the vanilla SFX files to wav or ogg and use those one with the external layer.

Cheers!
