### ISSUE TITLE
[ FF7 ] Noticable slowdown on lastmap

### ISSUE THREAD

**Issue by petfriendamy** [julianxhokaxhiu/FFNx#260]
Right before the fight with Bizarro Sephiroth, there's a scene with all the characters confronting Sephiroth. I've noticed a considerable slowdown when the background FMV starts playing. It doesn't seem to matter which graphics API I use.

Here's a video to demonstrate the issue. The left side is Steam version with no mods installed. Right side is 7th Heaven with "play without mods" selected.
https://www.youtube.com/watch?v=7_1705gV5Q8

OS: Windows 10 Home
GPU: NVIDIA GeForce GT 730
Driver: 30.0.14.7111
FFNx version: 1.9.0.71

**Comment by julianxhokaxhiu** [comment]
Thanks, I'll check what might cause this and let you know!

**Comment by julianxhokaxhiu** [comment]
I actually need a savegame to end up there to ease the test. Can you please share yours? Thank you!

**Comment by petfriendamy** [comment]
Here ya go. Doesn't look like the latest canary fixes it.
[save02.ff7.zip](https://github.com/julianxhokaxhiu/FFNx/files/6796066/save02.ff7.zip)

**Comment by julianxhokaxhiu** [comment]
Thank you. So I double checked the whole thing and basically it should have been fixed by this commit actually: https://github.com/julianxhokaxhiu/FFNx/commit/306e996d8040b5ba37acc791b865fef0de1f1bab

The issue though is that the field doesn't have the opcode `BGMOVIE` set, so the driver can't understand when to limit movies fps to the natural movie or to the current field one. This instead happens in the field `las4_2` ( 765 ) where the opcode is set and indeed now you run at full 30fps in that field.

I'll continue to investigate how the game engine did handle this scenario and patch accordingly.

**Comment by julianxhokaxhiu** [comment]
Solution found: canary is now being built. Feel free to try it and let me know how it goes. Here it seems to work fine now. Thanks for reporting!

**Comment by petfriendamy** [comment]
Yep, seems to be fixed now!
