### ISSUE TITLE
[ FF7 ] Huge Upside-down Cloud model

### ISSUE THREAD

**Issue by DLPB2** [julianxhokaxhiu/FFNx#295]
I've tried to find out why this is and I can confirm it is 100% not the field script itself.  It *could* be something that is specific to the 3 fields (bugin1c, md1_1, mtcrl_3)  bug it happens on.  The only commonality I have found is that the 'field scale value' is different with the fields above.  But that may just be a coincidence.

from Reunion Database

""Returning to md1_1 from md1_2 can cause Cloud's model to become huge and upside down. This happens more regularly after a battle. [This bug is confirmed to not be caused by field script. I think it might be some sort of weird memory issue - or something unique to this field compared to others.  Currently testing field scale value. - DLPB]

Note:  This happens at Mt Corel and in Bugenhagen's observatory also.""

The field scale value (walkmesh area info) is 1024 + for these 3 fields when usually it's 512.  Could be relevant but if that's the case we should also see this bug happen on bugin1b and so far we don't.  In any case, there's something seriously wrong here.  It happens intermittently. Sometimes it can take 100s of entries to the fields above before Cloud's model is corrupted.

Please see the following picture from Ori - tested with FFNx

https://drive.google.com/file/d/18U9OM7yWDznG2C--A0Todox6JcKPcslf/view?usp=sharing

**Comment by julianxhokaxhiu** [comment]
I've investigated a bit the whole thing and it seems the game is using a wrapper function `atoi` that calls itself `atol` ( which looks like the native implementation of [`atol`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/atol-atol-l-wtol-wtol-l?view=msvc-160) in the compiler ).

I have various idea on how to fix this:
1. Replace the built-in `atol` with the one from MSVC today implementation
2. Copy the string in a new buffer, add a NULL terminated character and return the converted value

I'll try first with 2 and if somehow it will not be working, I'll fallback to 1. But I think 2 should work well.

Look forward for commit updates on this issue.

**Comment by julianxhokaxhiu** [comment]
Some updates on the issue.

I've done some tests and checked what the games give and what we output, indeed using the new MSVC `std::atoi` implementation we can correctly convert the values, and I could catch some really weird cases where atoi behaved correctly now.

Some of them I catched in the logs:
```
[00001687] TRACE: ff7_atoi: 1024��1��< -> atoi -> 1024
[00001687] TRACE: ff7_atoi: 1024�o5 -> atoi -> 1024
[00001687] TRACE: ff7_atoi: 1024�L���$;fA��p=4� �2��; C -> atoi -> 1024
[00001687] TRACE: ff7_atoi: 1024�^��Qq4�a�!�1�4�q -> atoi -> 1024
[00001687] TRACE: ff7_atoi: 1024S/e/w/ -> atoi -> 1024
[00001687] TRACE: ff7_atoi: 102465
@&�&. "�1c0oo5:�0 -> atoi -> 102465
[00001806] TRACE: ff7_atoi: 1024��1��< -> atoi -> 1024
```

Feel free to test the latest canary and let me know if you're still able to reproduce the bug.

**Comment by julianxhokaxhiu** [comment]
Patch dropped. I'll try to find another way.

**Comment by julianxhokaxhiu** [comment]
I reworked the patch. I double checked the load model function and basically, the only safe way to fix this is by replacing only the atoi call in that function and ALWAYS use only the first 4 bytes of the buffer to convert, as inside there's a check that doesn't allow the model size to be bigger than 4096.

**Comment by DLPB2** [comment]
Yup that's how I do it too :)

**Comment by julianxhokaxhiu** [comment]
Thank you again for the hint, really appreciated!

**Comment by dolkow** [comment]
I heard about this in [a 4-8 Productions video](https://www.youtube.com/watch?v=-lMk2vVd5Dk), and reacted to this "worst things" quote:

> The model size is stored as a string - not a number. 1024 is literally 1 0 2 4 in memory [hex 31, 30, 32, 34]. So a function is called to convert this to a number [in this case 1024]. It's among the worst things I've ever seen in my life.

Allow me to speak in defense of the developers. :)

> It uses a look up table to decide when the string of numbers has ended. 0-9 are assigned value of 0x84 - a check is done for 0x4.

This sounds like there's a table of information about characters, which is queried for the implementation of `isdigit()`, e.g. something like this implementation that I just made up:

```
static inline int isdigit(int c) {
    return (char_attributes[c] & CHATTR_DIGIT) != 0;
}
```

The [PSYQ library seems to have done something very similar](https://github.com/FoxdieTeam/psyq_sdk/blob/3ce27b8f55f0c0485be3d8aa77d93551e9788fab/psyq_4.3/INCLUDE/CTYPE.H#L9), but in a macro instead. The +1 is because the C standard mandates that `isdigit()` handles all valid `char` values as well as `EOF` -- it is defined as `-1` in that library, and the content of the `_ctype_` array is presumably shifted one step up to accomodate this special value.

> If that is found, it will proceed to next number. if not, it decides the number has ended and the function returns the value.

Like @julianxhokaxhiu has mentioned above, this just looks like a standard `atoi()` implementation: convert until there are no more valid digits.

> It's REALLY bad. What's happening is that in memory 1 0 2 4 is followed by a random number from elsewhere

Yes, this is where it gets bad. Looks like they've just allocated 4 bytes for this text, regardless of the value. As I understand it, they use 4-digit values very rarely, so that's probably why they didn't notice the problem.

> if one of those values is 0x30-0x39 the game will think there is another number... and add that number too lol.

Yup, classic unterminated string problem. But that's really the only issue here; the conversion itself (lookup table + run-until-nondigit) is reasonable, and probably not even implemented by the game developers -- they just call `atoi()`.

Sorry about necro'ing this old post, I just couldn't resist. :)

**Comment by DLPB2** [comment]
They don't call "atoi" -  this issue is because the string was not
terminated and the mechanism they used to read it was broken.

**Comment by dolkow** [comment]
> this issue is because the string was not terminated

I agree.

> and the mechanism they used to read it was broken.

I disagree. The mechanism could be a valid (possibly inlined) implementation of `atoi`, with no inherent problems. My point is: using atoi on a nonterminated string is _sufficient_ to get the described behavior. 

Allow me to demonstrate:

```
#include <stdio.h>
#include <string.h>

#ifndef CUSTOM
#include <stdlib.h>
#else
// imagine this part is in some .h files of the c library

#define EOF (-1)

#define NM (_CHATTR_DIGIT | _CHATTR_HEX | _CHATTR_PRINT)
#define PU (_CHATTR_PRINT | _CHATTR_UPPER)
#define PL (_CHATTR_PRINT | _CHATTR_LOWER)
#define SP (_CHATTR_PRINT | _CHATTR_SPACE)
#define P  (_CHATTR_PRINT)
#define XU (PU | _CHATTR_HEX)
#define XL (PL | _CHATTR_HEX)

static enum { // probably shared, not static, in reality.
    _CHATTR_UPPER = 0x01,
    _CHATTR_LOWER = 0x02,
    _CHATTR_DIGIT = 0x04,
    _CHATTR_HEX   = 0x08,
    _CHATTR_SPACE = 0x10,
    _CHATTR_PRINT = 0x80,
} _charattr[] = {
    0, // for EOF (-1)
    /* 0x00 */  0, 0, 0, 0, 0, 0, 0, 0,
    /* 0x08 */  0,SP,SP, 0, 0, 0, 0, 0,
    /* 0x10 */  0, 0, 0, 0, 0, 0, 0, 0,
    /* 0x18 */  0, 0, 0, 0, 0, 0, 0, 0,
    /* 0x20 */ SP, P, P, P, P, P, P, P,
    /* 0x28 */  P, P, P, P, P, P, P, P,
    /* 0x30 */ NM,NM,NM,NM,NM,NM,NM,NM,
    /* 0x38 */ NM,NM, P, P, P, P, P, P,
    /* 0x40 */  P,XU,XU,XU,XU,XU,XU,PU,
    /* 0x48 */ PU,PU,PU,PU,PU,PU,PU,PU,
    /* 0x50 */ PU,PU,PU,PU,PU,PU,PU,PU,
    /* 0x58 */ PU,PU,PU, P, P, P, P, P,
    /* 0x60 */  P,XL,XL,XL,XL,XL,XL,PL,
    /* 0x68 */ PL,PL,PL,PL,PL,PL,PL,PL,
    /* 0x70 */ PL,PL,PL,PL,PL,PL,PL,PL,
    /* 0x78 */ PL,PL,PL, P, P, P, P, 0,
    /* 0x80 */  0, 0, 0, 0, 0, 0, 0, 0,
    /* 0x88 */  0, 0, 0, 0, 0, 0, 0, 0,
    /* 0x90 */  0, 0, 0, 0, 0, 0, 0, 0,
    /* 0x98 */  0, 0, 0, 0, 0, 0, 0, 0,
    /* 0xa0 */  0, 0, 0, 0, 0, 0, 0, 0,
    /* 0xa8 */  0, 0, 0, 0, 0, 0, 0, 0,
    /* 0xb0 */  0, 0, 0, 0, 0, 0, 0, 0,
    /* 0xb8 */  0, 0, 0, 0, 0, 0, 0, 0,
    /* 0xc0 */  0, 0, 0, 0, 0, 0, 0, 0,
    /* 0xc8 */  0, 0, 0, 0, 0, 0, 0, 0,
    /* 0xd0 */  0, 0, 0, 0, 0, 0, 0, 0,
    /* 0xd8 */  0, 0, 0, 0, 0, 0, 0, 0,
    /* 0xe0 */  0, 0, 0, 0, 0, 0, 0, 0,
    /* 0xe8 */  0, 0, 0, 0, 0, 0, 0, 0,
    /* 0xf0 */  0, 0, 0, 0, 0, 0, 0, 0,
    /* 0xf8 */  0, 0, 0, 0, 0, 0, 0, 0,
};

static inline int isdigit(int c) {
    int flags = _charattr[c+1]; // +1 to handle EOF
    return (flags & _CHATTR_DIGIT) != 0;
}

static inline int atoi(const char* s) {
    int v = 0;
    while (isdigit(*s)) {
        v *= 10;
        v += (*s - '0');
        s++;
    }
    return v;
}
#endif

// imagine this part is in a .c file

__attribute__((noinline))
int loadmodel(const char* sizestr) {
    int size = atoi(sizestr);
    /* blah blah blah */
    return size;
}

struct {
    char my_number[4];
    char morestuff[4];
} container;

int main() {
    memcpy(container.my_number, "1024", 4);
    memcpy(container.morestuff, "7abc", 4);
    printf("%d\n", loadmodel(container.my_number));
    return 0;
}
```

Compiling this with `-DCUSTOM` will use my custom implementation of `isdigit` and `atoi`, emulating what I believe their C library did. Compiling without that flag will use the normal `atoi` from standard libc.

[This godbolt link](https://godbolt.org/#z:OYLghAFBqd5TKALEBjA9gEwKYFFMCWALugE4A0BIEAZgQDbYB2AhgLbYgDkAjF%2BTXRMiAZVQtGIHgBYBQogFUAztgAKAD24AGfgCsp5eiyagA%2BudTkVjVEQJDqzTAGF09AK5smIAEzknADIETNgAcp4ARtikIACcAOzkAA7oSsT2TK4eXr7JqelCQSHhbFExCVbYNnZCIkQspERZnt48ldUZdQ1ERWGR0QZK9Y3NOW1D3b0lZVIAlFbo7qSonFwApD4AzMGoHjgA1GubzkOE6AB0SEe4a1oAghvbTLvuB0cnRKTBwJfXtw/3R4EGhMHA0fbOBQiAAqAHkALL/IHPPbYQ7HU70AgRX6bG6ArZVFT/AD0JP2BDYLGAwTRRCQBCU%2ByS3QpTOC%2ByU6A4%2B0u%2BzojCZ6HB9LRqH2WIipAaAE8kQTNmDaftcLCAGL7CAAWh4s3lDy2SpC%2B1C8M1pmcAAk7tDoQAlUwAEQAkgBxZ3Qw7xZz7C3W20Oy24AAaXp9fpt9tMqjtztC0L1CqNaNUCnNVsjDpjcc9a29vozAdMClUqlwdsTBsV2DoxtUAXT/qj2fjYYLTYdAVhAHVy5XHsn9iJVI3M9HY628%2BHC1Hh3dnLh%2B4aa8qR6Oiy2E0jl7W0cG0xBU22I0Wg8Gl9Xd/tgw3Dw2p%2B2x2f%2B/cJnZxcxPF6AEL7MnM0h0AiFgInoGVOSQBpsEwch9iYdAiE5ep31gjlSGwCRiBlc5/n2PDHyLEsyztdFHX2LR1C0NpcPwk8oy7XsSKOMiKK0PwaLwuiHRdd1c02FjKNkDiCKjM98OY8jKIADnIYSuNMOcF1IySeC0WT7nwkSswnPiBKktSkXiMjTFQSDpSIT41gAVm/ayyIkvNbI0/C1L/clBFIFV1U1HVK00kkACpJK0LR9gC8lyNg1zoqi2LIsi4TAuCqSwoitTh3IDL4pi7L1Lufygoo1TUrwnKyrimLEsK9QeBS8LSoqxrcoS5y8KSiifFC%2BqstUWDev2frBr64aqsknw6oioaBuG6bZqG0aKM2LryVNchVvW%2BE1s2jatrygrJM2CaTW2za5pmqbeoW9RpGWvDev3cgHqehRHpeh7Uz2/D2uuo6Pr%2Bl7/vIQGPquqzbuBgHIaBqGQdav9qqs36YZes7UcuuHvoANlu6ab0egJ8cJvG8frT62uqzHfoJ0maepumgfpq74nB%2BnaYZ9m2aZqmOYJtGZoMjHqv0krmvK0WyfhySpKO8XZcqwXJNiHGxZV2KrtiGXVbliXvpYZWmq1gX8q%2B6qWE1g2LZa43yckiJ9e18Wroic2HfKq7UHtw3Gvdl2vdyq7ME9y23YVijMF94PvdD9RsCD121ej7AI/jq39oomg479o20/UGhk6zvK80dI4nIBO43wIcVgixY1gkQxlCBpIgIDr/ZUFmH9hNbmgjGAJkJJMsyWAs0hrO/VANm/Hg7JLtzDh8Kf9hIfZINBRgvLVYT0KIJYmE1HvqX7nxMa0p03Q9DuwDACStBLwzi8BV9kMrikmBrtFW%2BH9ACAgDAmCGNuZkgpKA7o5Luwh9gADdlK302KXTSAB3Bk68W5KEbsQCAAUQGgPiPAzS%2BFoEBQkqpO%2BcNNLQMnhJTBTItT7DAFwLQ9C9RwOEppJQlCF6kOtl6B%2B3Dt67ygVwou25NhOGBPqf8lJqTKnpIyZkrI5EchYLycUApsD6nMMPT42J3BEGwOYKA8Fq60lmJWVu9B0AsEwGwLAVRf5CAAaZBowCCAAC9sBDFIDgvBeFW5pHccpL%2BP9/EeM%2BMwnxktQIsCQPsKJMS4mpS3tgHepA94hKEUZfUnj3C2E7nDJxnk2AylMEwfoo8bLSBniw/JZl9g2PQkMdwNAaBj0qVZYu1SHhGTbvIFgtJR6dP%2BK3KkwQIDeOEhwNgqAkgynscIPpIRSDnCKSUspsENg%2BFUj4SpPg/D7GkOEiZ2ApkzLmfUfpyyyChKaTQdZuz4ggQnrs2CByuGaSSF8YQNAIAbI2FZTA1lnBMA2bBCxVibE4HoGchZ0RlnFNKaUaIpi3n4X4ak8iGTHRcHmPQbgVl%2BDeAYfwdA3AfRciWCseemw%2BDkCINobF8wADWIArI%2BHOLVWImN4hLVZdIHgmNpDSCsoYbg0h%2BBsBZWpQlOhyAkq4PwJQIA1J0qJfMOAsAUAYDYEkBg0RKDUC1TqxgMRxCkDYAK4APBNidXIDgSBldsAADUCDYAQbCJIzBuA0oFHo0giqIARHpeQCIwRZRev4CG1gpAZSwgiLobAthw3kC1RwYQsI34yiDTgCI7hgDOAkPQRVvB%2BA4CpCYSQRLbUEHQrYAgkCPFBuwDHVAujVg0rrlUINkppTRtcDgIN2iJXFvmAfPuzrXXus9cWuQwgxASE4DIGdigVAaCDfoPwRgTAgHMCZQw2JFWQHmOgJINR/7cH2FqWENDHSQhhAiYl9bSBfBwAesZ7QE2nscKCUYrR/CgimGUgwKQ0inp/UB/Ip6AOIpiOMKoH7OjDCaG4Fogw4O1tqIhqDMxxiIbAzhyYtJpgDF1AsClC6cV4oJUGuV%2Bw7h2nhAK/YrpnA%2BitecNloUID4GIGQKlup%2BAqp0KY8gSAMI4BiG%2B3FXAxXkAlWDcg0riXcAVUq2l9LhPMutecKSGseDxC2FseIVkEixBFVwTYVHK1yoE%2Bp8g6qEDwHsxATV3IjV6qoPY7VuqTWWutba7A9qVjjrdR6wl3qGC%2Bv9YGytkaw3Tti9G2N8bE3TpTcwIg6awJZuwDmvNBai00tLcYYAFaZWEBrXYetRaZVNoTa2oNHapMyu7bKPtqwZWDvDSO3uShguTrC/wQQs7xCSEXUN5dahNCVv0G0TdZgLB7oiK%2Bo9J6MhFovVei9N6oRwnhA%2B6Iz6G2Hvfeh7wEAnB4b/ZgLDxG8ggYyJd4DBQmA3Zgyd09XQRjIbGO9hDBHiiAfw197Iv6JiNFe3MUjyxyNmfxQp6j571BSUxlqRjwBUDijYz4TU3GSCeUePxtTqqmWSrMzJuTUqEfyqsKpwT2K7OIGc2gVz3n9Webcz5q1fg7UOr66FpNProhRaDQlzN8XQ2JbjR%2BpNaW00Zuy7l/N9BC1JqK%2BW9rJbq3waq425t9XK2Na7diHtMo2sDq%2BEOvg3XD586nd6%2BQc7RuyHG8oSba6QCbEMMV7dC3JTLdlathx57L1KH20%2BggL74DzGsPBhw53v3fd/YEQjgO7vPcexBjIEPYMdAw90S7MfTufZ6Cn6DgxcOJ/L/9voZeSPkuh5DqTcPFOysR8j1H0h9jo8x5sdjOPCB4747MGzxORNiYGG%2B5l8mpMyZb9Zmnyr1MUa4D4cVpO5/KaJ0JhnjnGcoEWEQJIui2eGu86Edgqwkco7Rxj/YWP%2BDQR48%2Bgw43HcLud/IV3q7psGAQdKJIXWsOlmMqcqsIuiR%2BiEwo%2BwV%2BHeXet%2BWOmorgXmxqQ%2BI%2BQm8womViE%2BJO0%2Boqa%2B8mG%2B1Oiqi%2BqqO%2BGqIAB%2BEBJ%2BLOxq5%2BHA3AMBN%2BPe7GD%2BA%2BZAEeL%2BDuI27%2BS6X%2BU2Mq%2Bgnuf%2BLAABw6QB8OVm3AYBh%2Bui%2BwUBjBne3ed%2Bve2OEASBHOVKmww%2BW%2BDKY%2BWBEmOBakM%2BwBSmRBtOS%2BZmq%2Bsm6%2BVOaBuhzKXK7KVEUkPg8QXKmM2ybEZmFmEhIBm%2BdOwmUmVhhBdhwmj6aQDg0gQAA%3D%3D) shows the assembly and execution result of both.

Note that:
* My custom implementation ends up doing exactly what you've described: lookup table, bitmask, stops when the relevant bit isn't set.
* My custom implementation has no visible `atoi` call (because it's been inlined from either a function or a macro).
* Both output "10247" -- i.e. my custom implementation matches the behavior of the standard `atoi`.

So, again, I think the conclusion here should be that the string is unterminated, which causes the problem -- and that's a nice find, kudos! -- but there's nothing inherently wrong with how the game is _reading_ this value.

**Comment by julianxhokaxhiu** [comment]
> but there's nothing inherently wrong with how the game is reading this value.

How would you explain then the bug we had to fix?

**Comment by dolkow** [comment]
By the string being unterminated. That's wrong and bad. Using `atoi` (which in turn uses a lookup table and continues as long as there are digits) is not.

**Comment by julianxhokaxhiu** [comment]
To be honest I see this discussion as pointless because you're defending the C implementation of atoi like we're saying that's the problem, when we clearly had to fix a bad implementation on the FF7 engine side of things where they used atoi on top of non-null terminated strings, which is the problem we had to fix.

The fact the patch replaces atoi in the game engine is because is the most common entry point that is used across of many other subs. We're not doing it "because we don't like atoi".

**Comment by dolkow** [comment]
>  I see this discussion as pointless

Probably, but it's also _interesting_. :)

> you're defending the C implementation of atoi like we're saying that's the problem

I honestly thought you were, in this part:

>  It's among the worst things I've ever seen in my life. It uses a look up table to decide when the string of numbers has ended. 0-9 are assigned value of 0x84 - a check is done for 0x4. If that is found, it will proceed to next number. if not, it decides the number has ended and the function returns the value. It's REALLY bad.
