### ISSUE TITLE
[ FF7 ] Separated FMV audio loses quality.

### ISSUE THREAD

**Issue by wturner859** [julianxhokaxhiu/FFNx#369]
When using separated fmv audio tracks, the audio track loses a lot of quality. Sounds as if the file is playing at 150% volume or a crushed  .mp3. 

You can tell the difference by listening to the track on it's own:
[opening.zip](https://github.com/julianxhokaxhiu/FFNx/files/7982905/opening.zip)
and listening to it in-game with Cosmo Memory.

**Comment by wturner859** [comment]
Needs the eyes of @myst6re

**Comment by julianxhokaxhiu** [comment]
I think this happens because the source ogg audio uses a sample rate of `96000Hz` while the audio library we use I think goes maximum to `48000Hz` so of course, downsampling might get you there.

I'm not sure we're even able to touch that part and if we can tweak only for movies. This didn't happen with movies before because the way we decode the audio on movies, and the way we playback them now using the external audio layer are completely different and not compatible.

I'd suggest you trying to downsample those audio files to a more normal Hz frequency and try again first.

**Comment by wturner859** [comment]
fixed.
