### ISSUE TITLE
[ FF7 ] Broken lastmap field

### ISSUE THREAD

**Issue by satsukiyatoshi** [julianxhokaxhiu/FFNx#41]
This field show stanrge contrast issue in vanilla game.
No issue with external modded texture.
Probably related to the light animation palette (as not used with external textures files)

![Screen_Shot_004](https://user-images.githubusercontent.com/8547498/82123473-ef5f1d80-9799-11ea-8089-b9a33ff53dd9.png)

**Comment by julianxhokaxhiu** [comment]
I did some personal tests and it seems this is broken on native D3D too. With software rendering although there's some light animation in place. Looks like we miss the overall light animation rendering. Another TODO in the list :)

**Comment by julianxhokaxhiu** [comment]
Light animation is in place actually also with vanilla textures in FFNx, so it all boils down to a weird white texture being passed for rendering. I'll continue to investigate what it should that be.

**Comment by julianxhokaxhiu** [comment]
I found a PSX gameplay walkthrough and it sees the rendering logic is completely wrong! In both stock PC game and also on our side: https://youtu.be/KYZymFDSThQ?t=647

Fixing that should fix the issue actually.

**Comment by julianxhokaxhiu** [comment]
After some investigation I found out the core issue of this bug is a broken `flevel.lgp` file ( or language related one ).

In order to fix it, you need to use [makoureactor](https://github.com/myst6re/makoureactor) and open your LGP file.

Then in the left list pick the item named `lastmap` and click on the image that will appear on the bottom-left. This window should appear.

![image](https://user-images.githubusercontent.com/1237070/82161327-1140c900-989c-11ea-8af8-a251f674fe13.png)

Hit `Repair`, close the window the click Save.

This stage will be crystal clear as expected :)

Proof:
![image](https://user-images.githubusercontent.com/1237070/82161336-24539900-989c-11ea-8140-1612a4aae083.png)

**Comment by myst6re** [comment]
This kind of bug is present on two maps:
 - lastmap
 - fr_e

On both Makou Reactor is able to restore the original data. My fix try to reindex palette ID if it is clearly wrong. I don't remember if the fix is perfect, but I think so. We can make it perfect by recreating the background from the PS format. In fact the tile list is present in both formats (PS and PC) in field files from the PC version.

**Comment by julianxhokaxhiu** [comment]
That would be great. Thank you!

I'll close this issue and marked as solved so anyone who may cross around this topic has a reference on how to fix it :)
