### ISSUE TITLE
[ Common ] CMakePresets.json does not pick RelWithDebInfo by default

### ISSUE THREAD

**Issue by ChthonVII** [julianxhokaxhiu/FFNx#577]
**Describe the bug**
Some commit later than b6bf503 and not later than f7cb728 has badly broken the progression system in ways that first become very obvious at Wall Market. The gun-equipped vending machine hands out the Premium Heart the first time it's encountered. The weapon shop owner is ready to sell the sneak glove on your first meeting. The street in front of the Honeybee Inn has the wrong NPCs (only one Shinra guard at the door), so progress beyond this point becomes impossible. Also, if you leave that map, then come back, then try to leave again, Aerith will separate from Cloud to interact with NPCs who aren't there, getting stuck.

**To Reproduce**
1. Start a new game a play through to Wall Market. (Alternatively, the bottom save in the attached file is immediately before entering Wall Market for the first time.)
2. Notice progression is broken.

**Expected behavior**
Progression is not broken.

**Workaround**
Revert to older FFNx binary.

[save03.ff7.zip](https://github.com/julianxhokaxhiu/FFNx/files/11631128/save03.ff7.zip)

**Comment by julianxhokaxhiu** [comment]
I don't see how a stack bump would break such in-game functionality since we didn't touch anything related. But I'd appreciate if anyone can replicate this bug.

Again, Stable 1.15 vs canary is enough.

Thank you in advance.

**Comment by ChthonVII** [comment]
I'm not having the same issue with the most recent canary.

This suggests that it's caused by something in my build environment. I've got a theory, but it will take awhile to check out. I'll report back.

**Comment by julianxhokaxhiu** [comment]
> This should probably be changed, since it's unexpected and inconsistent with what the read-me says the default is.

Feel free to do some tests and open a PR if it works :) I'll be happy to merge it. `RelWithDebInfo` should be the default one which provides a good balance between performance and debugging. So if that's not the case with `CMakePresets.json` let's fix it.

About the rest, it is expected to have a slower runtime if you build with `Debug` because it's exactly for debug purposes like in every other software you build. If you want better performance you must use other profiles, like Release, MinSizeRel. RelWithDebInfo sits somewhere in the middle and so far worked fine for us.

**Comment by julianxhokaxhiu** [comment]
First profile to be built by default now is going to be `Release` like the one used here on the CI. Second to that is `RelWithDebInfo`. This should provide at least a match in performance of what you expect by default.
