### ISSUE TITLE
[ FF7 ] Aerith Eye Texture

### ISSUE THREAD

**Issue by KuraudoXS** [julianxhokaxhiu/FFNx#589]
Buried in the code we can notice there was an instance where Aerith would change eye texture in the Sleeping Forest and Cid would change mouth texture in the Gondola, the Cid mouth texture should be present in PC version but achievable only by updating model IIRC.

**_While the Aerith eye texture 3 is not in PC version at all and would need a new logic in within the engine itself most likely._** 
See below field name and the exact moment in game.

1) "Aerith's eye texture 3 used when she is laughing during Cloud's dream after the Temple of Ancients." (5:04:37 - https://youtu.be/ub0qHDFZayE?feature=shared&t=18277 ) (slfrst_1 )
2) ~~"Cid's mouth texture 2 (open mouth) is used in the scene where he is with Cloud in Gold Saucer's Round Square." (1:19:33 - https://youtu.be/2hAg9tzCHpk?feature=shared&t=4773 ) ( bwhlin and bwhil2 )~~

Could be nice to have this petit détail restored.

Source: https://tcrf.net/Final_Fantasy_VII
Eye Texture 3: AUHC.bmp https://drive.google.com/file/d/1Naebiqq1MqsXeiqIz5GmtFWOc5xA0fNa/view?usp=sharing

**Comment by julianxhokaxhiu** [comment]
I had a quick look at this issue and so far I found the following info around it:
- The model being used in that field is AUFF
- The model is correctly mapped to use Aerith eyes ( https://github.com/julianxhokaxhiu/FFNx/blob/master/src/ff7/field/model.cpp#L328-L329 )
- The game uses `ea_eye2.tim` (Left eye) and `ea_eye2r.tim` ( Right eye ) natively

Since the game has no room for custom eye textures, I think the fix has probably to happen in the field data itself, using a custom Aerith model and using a custom model to fix the eye texture.

I can't see any other way to fix it via code as there's nothing to fix actually. Open for feedback, I'll change the status of the issue in the meantime.

**Comment by julianxhokaxhiu** [comment]
First part is now done in code. The second part has to be provided externally with a mod.

If you enable `trace_opcodes = true` you'll now see this message that will give you a hint for which custom eye texture the game is trying to load:
```
[00007252] TRACE: opcode[KAWAI]: num_params:7,subcode:0x0,left_eye_index:2,right_eye_index:2,mouth_index:0
[00007252] TRACE: opcode[KAWAI]: Custom left eye texture not found: direct/flevel/c_eye2_2.TEX
[00007252] TRACE: opcode[KAWAI]: Custom right eye texture not found: direct/flevel/c_eye2r_2.TEX
```
