### ISSUE TITLE
[ FF8 ] Decreased performance on world map when using external textures

### ISSUE THREAD

**Issue by someyoungguy00** [julianxhokaxhiu/FFNx#701]
**Describe the bug**
When using external textures from the FF8 world map performance decreases and frame rate drops to about 15fps.

**To Reproduce**
Use external textures in the "mods\Textures\world\dat\wmset\" folder, no perfomance impact with other \world\ folders!

**Expected behavior**
Full FPS in world may be in different if full vram page is set as in Tonberry instead of using sinle pages for 16x16 textures!

**GPU (please complete the following information):**

- Brand [Intel HD 4000]
- Driver Version [e.g. NEWEST]
- NOTE: This is an older GPU so performance impact may not be as bad in newer computers
- Noticed no performance impact on any other textures in other parts of game

**Tested with**

- Latest canary 1.19.1.40
- Same issue persists in 1.19.1.0

**Comment by julianxhokaxhiu** [comment]
@myst6re FYI

**Comment by someyoungguy00** [comment]
To add to this i'm using my pack i converted from the old Horizon Pack (Legacy) - https://drive.google.com/file/d/11ocgYlzCxYDD0JKas1ur7PUr3p_WG1-V/view?usp=sharing

"mods\Textures\world\dat\wmset\section38" is the worst impact (16fps)
everything other section in "mods\Textures\world\dat\wmset\" only has a slight impact (26-30fps)

**Comment by myst6re** [comment]
Several recommendations:
- Do not use texl, prefer per vram page replacement (section38/texture0_texture1_16_0_0.dds)
- Prefer per vram page replacement or lower resolution for animated textures **AND** textures that are impacted by the animated textures (because there are on the same VRAM page), see the full list below

Per VRAM page replacement for animated textures will be soon available via the PR #696 

## Animated or impacted by animated textures

### VRAM page 13

- world/dat/wmset/section38/texture9 rect=(832, 64, 24, 96)
- world/dat/wmset/section38/texture12 rect=(880, 112, 4, 16)
- world/dat/wmset/section38/texture13 rect=(884, 112, 4, 16)
- world/dat/wmset/section38/texture14 rect=(880, 128, 16, 16)
- world/dat/wmset/section38/texture15 rect=(880, 96, 16, 16)
- world/dat/wmset/section38/texture24 rect=(892, 112, 4, 16)
- world/dat/wmset/section38/texture25 rect=(880, 144, 4, 16)
- world/dat/wmset/section38/texture26 rect=(880, 88, 8, 8)
- world/dat/wmset/section38/texture27 rect=(856, 128, 8, 32)
- world/dat/wmset/section38/texture28 rect=(884, 80, 4, 8)
- world/dat/wmset/section38/texture29 rect=(888, 80, 8, 16)
- world/dat/wmset/section38/texture30 rect=(872, 128, 8, 32)
- world/dat/wmset/section38/texture31 rect=(864, 128, 8, 32)
- world/dat/wmset/section38/texture32 rect=(864, 160, 32, 32)
- world/dat/wmset/section38/texture33 rect=(880, 64, 16, 16)
- world/dat/wmset/section38/texture34 rect=(872, 64, 8, 32)
- world/dat/wmset/section38/texture35 rect=(832, 160, 32, 32)
- world/dat/wmset/section42/texture12 rect=(888, 112, 4, 16)

### VRAM page 28

- world/dat/wmset/section17/texture0 rect=(832, 384, 32, 64)
- world/dat/wmset/section17/texture1 rect=(864, 384, 32, 32)
- world/dat/wmset/section17/texture2 rect=(864, 416, 32, 32)
- world/dat/wmset/section38/texture16 rect=(800, 384, 32, 64)
- world/dat/wmset/section38/texture17 rect=(768, 448, 32, 64)
- world/dat/wmset/section38/texture18 rect=(800, 448, 32, 64)
- world/dat/wmset/section38/texture19 rect=(832, 448, 32, 64)
- world/dat/wmset/section38/texture20 rect=(768, 384, 32, 64)
- world/dat/wmset/section38/texture23 rect=(864, 448, 32, 64)

**Comment by julianxhokaxhiu** [comment]
@someyoungguy00 can you please provide some feedback? Did the answer and the PR solve this issue?

**Comment by julianxhokaxhiu** [comment]
Closing the issue since it is stale.
