### ISSUE TITLE
[ FF8 ] World Map Ambience & World Map Battle Ambience

### ISSUE THREAD

**Issue by MikeHolmesAudio** [julianxhokaxhiu/FFNx#719]
## Summary

Ambient sounds added to the world map & world map battles  

### Basic example

I'd like sound volume to be effected by walkmesh id, this is so I can add multiple sounds to the world map and field. For example when we get closer to the coast we can hear the sea, when we get closer to a forest we can hear birds and trees. 

Also battlefields on the world map do not create a bat_ id, meaning I can't currently add ambiences to world map battles, making it jarring compared to the rest of the game. 

### Motivation

We are doing this to move our modding capabilities forward, something that hasn't been done yet in final fantasy modding. And also to make the SFX-J experience consistent throughout the entire game. And It would allow you to add multiple ambiences to a single scene with positioning

**Comment by julianxhokaxhiu** [comment]
> I'd like sound volume to be effected by walkmesh id, this is so I can add multiple sounds to the world map and field. For example when we get closer to the coast we can hear the sea, when we get closer to a forest we can hear birds and trees.

This would require a new layer in the Ambient side which we currently do not support and would require massive work I don't have time at the moment to take. However what I can offer as a middle term solution is to provide an ambient layer ( in field mode only ) that lookups for field ambient files using also the triangle ID, this would require you to provide different audio files with different volumes attached. But I do understand the complexity, so I can try to add a `volume` parameter to the config block so you can re-use the same file, but load it with different volumes. Up to you which one you prefer, let me know :)

> Also battlefields on the world map do not create a bat_ id, meaning I can't currently add ambiences to world map battles, making it jarring compared to the rest of the game.

This was fixed in [this commit](https://github.com/julianxhokaxhiu/FFNx/commit/34fada155b51bc92249127d748e81bd4f06d6428), you should now be able to get correct `bat_XX` lookups for Ambient in both field and worldmap in battle.

**Comment by MikeHolmesAudio** [comment]
> But I do understand the complexity, so I can try to add a `volume` parameter to the config block so you can re-use the same file, but load it with different volumes. Up to you which one you prefer, let me know :)

This would be a favourable option, thank you very much! That is literally what I wanted, I may need some guidance on how to achieve this.

**Comment by julianxhokaxhiu** [comment]
Ambient can now be customized by triangle IDs in fields, and you have a new flag `volume` available in the `config.toml` file as well.

**Comment by MikeHolmesAudio** [comment]
Legend, thank you very much.
