### ISSUE TITLE
[FF7] The terrain platform during Neo Bahamut's summoning is not rendered on OpenGL

### ISSUE THREAD

**Issue by daedrixxx2** [julianxhokaxhiu/FFNx#95]
When summoning Neo Bahamut the terrain platform on which the enemies stand that is normally lifted to the sky and is then dissolved by Gigaflare is not rendered (or it's simply invisible). I don't remember if this was the case with Aali's driver too, maybe it's triggered by the upscaled battle textures? In regular PSX and unmodded PC versions it was rendered.

**Comment by Neffina** [comment]
this error only occurs with the 60 fps mod, if the mod is deactivated, the error is not there.

**Comment by daedrixxx2** [comment]
But I don't use any 60 fps mod. The only things that MIGHT remotely relate to 60 fps are "refresh _rate= 0" (uses current screen refresh rate, i.e. 60hz) and "enable_vsync= yes" in the config file.

**Comment by Neffina** [comment]
what version of ffnx are you using?

**Comment by Neffina** [comment]
I use version 1.7.2.134 and I have this problem not only when I activate the 60 fps mod

**Comment by daedrixxx2** [comment]
I have the latest canary, 1.7.2.179

**Comment by Neffina** [comment]
mmmh I'm just thinking about what's up to you, do you have the steam or 98 version, have just tested it again and I don't have the problem

**Comment by Neffina** [comment]
this is what my config looks like

**Comment by Neffina** [comment]
# FFNx config file

### HOW TO: ###################################################################
# Options may be commented by default with an initial # character.
# Remove the initial # character to set the configuration flag.
# -----------------------------------------------------------------------------
# Unless options are specified, you can either disable or enable a flag.
# Enable: yes
# Disable: no
###############################################################################

# =============================================================================

###############################################################################
# COMMON OPTIONS FOR BOTH FF7 AND FF8
###############################################################################

#########################
## DISPLAY
#########################

#[RENDERING BACKEND]
# Available choices are:
# - 0: Auto ( default, will pick the best rendering backend for your GPU )
# - 1: OpenGL ( works fine on Intel/Nvidia, MAY break on AMD )
# - 2: Direct3D9 ( Tech Preview: Not Recommended )
# - 3: Direct3D11 ( works fine under any GPU on Windows )
# - 4: Direct3D12
# - 5: Vulkan
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#renderer_backend = 0

#[FULLSCREEN]
# If off, it will run in window mode.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
fullscreen = yes

#[RESOLUTION]
# Resolution of the game.
# Default (value = 0):
# - Window mode will use 640x480
# - Fullscreen mode will use your desktop resolution
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#window_size_x = 0
#window_size_y = 0

#[INTERNAL RESOLUTION SCALE]
# The scale is in multiples of 640x480
# The scale factor is used to render internally at a larger size then the display, this will then be downscaled to the games current resolution
# This is required to avoid visual glitches that may happen when the game is not rendered in a 4:3 aspect ratio.
# This is optional for native 4:3 resolutions, but it will enhance visual quality ( like Nvidia DSR ).
# Default = 2
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#internal_resolution_scale = 2

#[PRESERVE ASPECT]
# Preserve original game aspect ratio of (4:3) by adding black bars on the left and right side (if needed)
# When off the game will be stretched to fit the window's aspect ratio; Be aware the game may look wrong though.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
preserve_aspect = yes

#[ENABLE VSYNC]
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
enable_vsync = yes


#[REFRESH RATE]
# Screen refresh rate.
# Default is 0 = use current screen refresh rate
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#refresh_rate = 0

#[LINEAR FILTERING]
# Allow the usage of linear filtering for textures.
# Please note: some things look slightly better with this option on, but alot of textures just lose their detail.
# This option only affects low-res textures, high-res replacements will still be filtered where appropriate.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
linear_filter = yes

#[ANTIALIASING]
# Enable antialiasing filtering, this is done in the last pass when downsampling from the current supersampled rendering ( based on internal_resolution_scale logic )
# Available choices are:
# - 0: Disabled ( Default )
# - 2: 2x
# - 4: 4x
# - 8: 8x
# - 16: 16x
# If you set any value that is different than those, it will pick the higher option ( eg. if you pick 6 it will be 8, if you pick 1 it will be 2, and so on ).
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
enable_antialiasing = 16

#[ANISOTROPIC]
# Enable anisotropic filtering, for high-res textures and overall rendering
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
enable_anisotropic = yes

#########################
# AUDIO
#########################

#[USE EXTERNAL MUSIC]
# This flag will enable/disable the support of an enhanced music layer to reproduce music in-game.
# If you leave out the default configuration
# FFNx will autodetect your environment and will set it to the best available option.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
use_external_music = yes

#[EXTERNAL MUSIC PATH]
# Path of the external music files
# Will try to load from this path before using the default for your Version of the game
# Defaults:
# - FF7 1998: music/vgmstream ( 7h-era compatibility )
# - FF7 eStore: data/music_ogg
# - FF7 Steam: data/music_ogg
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
external_music_path = data/music_ogg

#[EXTERNAL MUSIC EXTENSION]
# The type of file to search for. By default is ogg.
# Supported extensions: 
# - https://github.com/losnoco/vgmstream#supported-file-types
# - Any additional or any type supported by your loaded winamp_in_plugin
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
external_music_ext = ogg


#[EXTERNAL WINAMP PLUGIN SUPPORT]
# These flags will allow you to make use of compatible in_* and out_* DLL plugins you were used to load on Winamp itself.
# Through these flags you can for example decide to use an input plugin to play something FFNx never though about ( like MINIPSF files )
# and output the sound data to your custom plugin which may add custom reverb and much more.
# By default winamp_in_plugin will use the built-in VGMStream layer.
# By default winamp_out_plugin will use the built-in output layer.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#winamp_in_plugin =
#winamp_out_plugin =

###########################
# Video Player Options
###########################

#[ENABLE FFMPEG VIDEOS]
# This flag will enable/disable the support of FFMpeg layer to reproduce movies in-game.
# Default Value depends on game version.
# - FF7 1998 - yes
# - FF7/FF8 Steam - yes
# - FF8 2000 - no
# It is suggested to keep the default behavior unless you really know what are you doing.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#enable_ffmpeg_videos = yes

#[FFMPEG VIDEO FILE EXTENSION]
# The type of file that the ffmpeg layer will search for. Default is avi.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#ffmpeg_video_ext = avi

###############################
# MUST SET FOR VERSIONS BELOW
# FF7 2012   FF7 STEAM
# FF8 2013   FF8 STEAM
###############################
# The folder name in your game Documents path ( for eg. for FF7 is "C:\Users\JohnDoe\Documents\Square Enix\FINAL FANTASY VII Steam\user_XXXXXXX")
# Use this only if you have MORE THAN ONE user_* directories. If not, just leave this commented as the driver will autodetect the directory.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#steam_game_userdata = user_12345678

########################
## MODDER OPTIONS
########################

#[TEXTURE PATH]
# Mod directory where textures will be loaded from
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#mod_path = mods/Textures

# Show every failed attempt at loading a .png or .dds texture
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#show_missing_textures = no

# Dump internal textures to PNG files in the mod_path
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#save_textures = no

# This path is where the Hext patching layer will look for txt files.
# The path will ALWAYS have appended:
# 1. The game name ( if FF7 it will be "ff7/", if FF8 will be "ff8/")
# 2. The game language ( for eg. if ff7_en it will be "en" )
# The resulting path will then be "<hext_patching_path>/ff7/en", if you run for eg. FF7 English
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#hext_patching_path = hext

# This path will define where the driver will look first, allowing you to override core game files, if needed
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#override_path = override

#[SPEEDHACK]
# Set the step when increasing the speedhack speed
#~~~~~~~~~~~~~~~~~~~~~~~~~~
#speedhack_step = 0.5

# Set the limit of the speedhack multiplier
#~~~~~~~~~~~~~~~~~~~~~~~~~~
#speedhack_max = 8.0
#speedhack_min = 1.0

#[EXPERIMENTAL]
# Enable support for animated textures.
# WARNING: This flag MAY degrade the gameplay performance. Enable at your own risk.
#~~~~~~~~~~~~~~~~~~~~~~~~~~
#enable_animated_textures = no

##########################
# DEBUGGING OPTIONS
# These options are mostly useful for developers or people reporting crashes.
# Please do enable them only when required.
##########################

# Enable Dear ImGui overlay windows that show debug information.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#enable_debug_ui = no

# Set hotkey to toggle the debug information windows.
# This is specified by a virtual-key code hexadecimal value, see: https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#debug_ui_hotkey = 0x7B # VK_F12

# Display the verion of FFNx in upper right corner ( when fullscreen ) or in the title bar ( when windowed )
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#show_version = yes

# Display frames per second counter in upper right corner ( when fullscreen ) or in the title bar ( when windowed )
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#show_fps = no

# Display Rendering backend in upper right corner ( when fullscreen ) or in the title bar ( when windowed )
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#show_renderer_backend = yes

# Display some real-time debug information
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#show_stats = no

# Enable logging
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#show_applog = yes

# Show on screen error messages ( only on fullscreen )
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#show_error_popup = no

# Enable this flag if you want to see more verbose output from the backend renderer.
# Usually useful for debug pruposes. Do not enable otherwise.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#renderer_debug = no

# Creates a full crashdump file if the game crashes. Useful to be analyzed with WinDbg when reporting issues.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#create_crash_dump = no

# Various flags which will help in further debugging the game engine logics.
# Some flags may not generate any output depending on the game you play.

# trace_all - Dump in the logs whatever APIs is being called from the Engine in FFNx. Overrides all the others below.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#trace_all = no

# trace_movies - Dump in the logs only APIs that has to do with movie playback
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#trace_movies = no

# trace_music - Dump in the logs only APIs that has to do with music playback
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#trace_music = no

# trace_fake_dx - Dump in the logs only APIs that has to do with directdraw emulation
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#trace_fake_dx = no

# trace_direct - Dump in the logs only APIs that has to do with LGP loading
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#trace_direct = no

# trace_files - Dump in the logs only APIs that has to do with filesystem operations
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#trace_files = no

# trace_loaders - Dump in the logs only APIs that has to do with internal textures overrides
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#trace_loaders = no

# vertex_log - Dump in the logs current engine vertex data being passed to the GPU for drawing
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#vertex_log = no

# uniform_log - Dump in the logs current engine uniform data being passed to the GPU shaders
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#uniform_log = no

# Show debug info regarding movie synchronization.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#movie_sync_debug = no

###############################################################################
# OPTIONS ONLY FOR FF7
###############################################################################

## ENHANCEMENTS

# Include armor in magic defense calculation
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
mdef_fix = yes

## ADVANCED OPTIONS - Don't fiddle with these unless you know what you're doing.

# Enable alpha blending for textures without an existing blending effect
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
fancy_transparency = yes

# Skip movie frames if necessary.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#skip_frames = no

## MODDER OPTIONS - These options are mostly useful to modders and should not be enabled during normal play.

# This is the path where files where be read directly, instead then reading them inside the LGP archives.
# For example: if FF7 is looking for aaab.rsd in char.lgp, this option will make it open direct/char/aaab.rsd first,
# If this file doesn't exist it will look for the original in the LGP archive
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#direct_mode_path = direct

# This is the path where your savefiles will be read.
# Notice that the path will be relative to your FF7 Game install directory, where usually the "save" directory is stored.
# PLEASE NOTE: THIS IS A VALID OPTION ONLY FOR FF7 1998/eStore edition. It will NOT work on the Steam edition!
#save_path = save

## DEBUGGING OPTIONS - These options are mostly useful for developers or people reporting crashes. Please do enable them only when required.

# Dump in the logs more verbose error messages coming directly from the engine
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#ff7_more_debug = no

###############################################################################
# OPTIONS ONLY FOR FF8
###############################################################################

## ENHANCEMENTS

# FF8 by default is used to pause the game when the window has no focus. This flag will override this behavior and will allow you to NOT pause the game and keep it running, if set to yes.
# This flag may be useful for streamers which may not want the game to be paused while switching the focus on another window.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#ff8_keep_game_running_in_background = no

## DEBUGGING OPTIONS - These options are mostly useful for developers or people reporting crashes. Please do enable them only when required.

# Show the PSX SSIGPU VRAM window
#~~~~~~~~~~~~~~~~~~~~~~~~~~~
#ff8_ssigpu_debug = no

**Comment by daedrixxx2** [comment]
Steam. I use satsuky's battle, world map and fields textures upscale (v4, .dds). I use renderer_backend= 1 (OpenGL), everything else is identical to your config.

**Comment by Neffina** [comment]
also that you left the # away

**Comment by Neffina** [comment]
have you also deactivated all mods and then tried it?

**Comment by daedrixxx2** [comment]
I delete the # on every line that I edit. I also play completely vanilla but for the background upscales and psx music. Of course the bug doesn't occur without FFNx

**Comment by Neffina** [comment]
do you play over 7th heaven?

**Comment by daedrixxx2** [comment]
I think it's like a bug I used to have with Aali's driver. With it every attack that had the same animation of Quake 3, instead of having rocky textures raising up from the terrain, I had garbage text and numbers, probably coming from menu_us.lpg. This happened with both upscaled textures and vanilla installation (just Aali's driver).
Now with FFNx this bug has disappeared.

> do you play over 7th heaven?

No.

**Comment by Neffina** [comment]
can you test the game times without you using mods by renaming the mods folder and only using the FFnx driver to exclude that it comes from the mods?

**Comment by daedrixxx2** [comment]
Now we know it doesn't come from the textures upscale. Tried it without them and it still happens.

**Comment by Neffina** [comment]
then I have to pass, I just don't understand why this mistake doesn't occur to me, maybe someone else can help you

**Comment by daedrixxx2** [comment]
Thanks for trying, anyway.

I think it must have something to do with fps, and/or refresh rate... As you said that if you enabled the 60 fps battles hack you had the same bug. But I've never used such mods, my in game fps in battle are 15.

**Comment by Neffina** [comment]
15 fps are also standard, but something has to be different from mine or any mod that causes you to fail

**Comment by julianxhokaxhiu** [comment]
Are you referring to this one? Looks good to me. I'll try now with your combintation of options, but works fine on default settings.
![image](https://user-images.githubusercontent.com/1237070/94349757-ea638200-0047-11eb-84c7-6b2b66b3c99f.png)

**Comment by daedrixxx2** [comment]
I use OpenGL... maybe with DX11 it works?

**Comment by julianxhokaxhiu** [comment]
You're right, it seems on OpenGL something is not correctly interpreted. I'll try to investigate now :) Thanks
![image](https://user-images.githubusercontent.com/1237070/94349840-c2285300-0048-11eb-9fb9-b47bd5c0c1f1.png)

**Comment by julianxhokaxhiu** [comment]
I've found the root cause, but I will need to investigate further. It seems the OpenGL renderer on bgfx is not binding the texture data correctly, although it should be there.

**Comment by julianxhokaxhiu** [comment]
Allright, issue found and resolved :) Should be good on OpenGL now.
